### PR TITLE
WHM: Tetragammaton feature and Devine Benison option

### PR DESCRIPTION
**Pull request by NikkoXIV**
WHM: oGCD Heals/Shields feature
 - Adds Tetragammaton to Cure II, Option for oGCD and GCD with HP slider
 - Adds Divine Benison to Cure II, Option for oGCD and GCD (https://github.com/Nik-Potokar/XIVSlothCombo/issues/501)

WHM: CDs on Glare/Stone feature (Enhancement)
 - Adds No Swift Opener Option to CDs on Glare/Stone (https://github.com/Nik-Potokar/XIVSlothCombo/issues/519)

BLM: Changed references of CanWeave to CanSpellWeave
BLM: Fixed Sharpcast from appearing randomly on Simple BLM when it couldn't be used

Framework; Adjustment to CanSpellWeave to reveal oGCDs earlier to allow the game to queue.
 - Note: The timing is still tight for high SPS builds, but should help casters overall.

### CODE REVIEW

**Comment by k-kz** [comment]
How long are the animation locks for Tetragrammaton & Divine Benison?
Is a 0.1s `canWeave` not cutting it a little close for pushing the GCD?

**Comment by NikkoXIV** [comment]
I'm going to update the PR.  I added something to CanSpellWeave to show the oGCD a half-second before you can actually weave.  This should allow the game to queue the oGCD to be executed immediately upon release.  The result being that I can leave the `canWeave` setting at default but it should be more functional for high SPS builds.  I also added more options and a HP percent slider on Tetragammaton.

**Comment by Tsusai** [comment]
k-kz asked this in discord earlier
https://cdn.discordapp.com/attachments/959778428024926258/965693528887939093/unknown.png

I'm no WHM, but based on the comment, are you trying to get the larger number between your existing benisonStacks and RemainingCharges?
if so, Math.Max may be your friend, no if required. https://www.geeksforgeeks.org/c-sharp-math-max-method

**Comment by NikkoXIV** [comment]
I get the build error that Math doesn't exist in the current context.  So I'm guessing we don't include the class by default?

**Comment by NikkoXIV** [comment]
Resolved the conflicts with 3.0.11.0.

**Pull request merged**
