### PR TITLE
[Healers & PCT] Bug fixes and new utility features

### PR DESCRIPTION
**Pull request by StackBLU**
[WHM]
- Removed Cure 3 MP slider
- Fixed Cure 3 never being used for Simple AoE Heals (would always use Medica 1 instead)
- Fixed swift/thin air/raise feature (would get stuck on swiftcast before)
- Raised priority of Afflatus Solace above Regen (unlike aspected benefic, there is no immediate heal from regen - this logic will likely need to be adapted later on, as now regen is only used if you have no lilies)
- Added Misery check to Simple STHeals (allowed overcapping before)

[AST]
- Added lightspeed protection option
- Re-ordered IDs and UI ordering, as it didn't make much sense before

### CODE REVIEW

**Review by StackBLU — COMMENTED** [review]
Sorry for the mess of commits - still learning how this works. I think I have everything that I actually wanted to upload good to go now though.

**Comment by zbee** [comment]
You should reset AST options or not rearrange all of its options' IDs, it misinterprets all of my existing settings.

DNC previously did a reset of options [here](https://github.com/Nik-Potokar/XIVSlothCombo/pull/1266/commits/342996f3b9c53038938dafeee5e9a9805413baeb), which I was going to go off of, but Tartarga mentioned on #1412 that all configs were wiped for 7.0; they may have more information on how to do this correctly.

**Comment by Taurenkey** [comment]
Rejecting this PR.

Starting with PCT, you've removed options altogether but added Lucid (which I have yet to find a use for with the job since it has no rez utility meaning MP is less of a factor for the job). You removed the combined aetherhues feature which is a no go since not everyone uses the full one button rotation but like having reduced button bloat.

Next, by reordering a lot of things you've made this review much harder to determine what's actually new and what's been removed, so rather than risk more options being removed because of hard to read diff checks, I'm rejecting it on this basis too.

Lastly, resets don't just get thrown out willy-nilly, there needs to be a significant reason for it. There was nothing here that supports the need for a reset.

**Comment by StackBLU** [comment]
Combined aetherhues was not removed, it was split into advanced mode ST and
AoE like all the other classes. Same function, two checkboxes now instead
of one (which allows for more customizability in the future when adv mode
gets fleshed out).

As for the reorganizing of everything in healers, this was something I felt
was very much needed. There are inconsistencies between all of them. This
PR would have aligned all of them to follow the same pattern, which would
make developing easier.

If you want all the changes without the cleanup, I can do another one.

**Pull request closed without merging**
