### PR TITLE
[MNK] Internal Changes + UI Cleanup

### LINKED ISSUE #1056: [MNK] TargetHP% slider for Demolish & RoE spam prevention
SAM have added a TargetHP% slider for Higanbana use in single target combo since last update, would it be possible to have the same feature to MNK by using Snap Punch and ignore Demolish?

Another request, Can MNK get a Riddle of Earth Protection to prevents the wrongly input to use the RoE twice?

### PR DESCRIPTION
**Pull request by Kagekazu**
- Demolish %HP slider
- UI cleanup
- added Simple mode - Advanced Mode for ST and AoE
- added old options to advanced mode
- removed old options from simple mode
- Meleechecks for ElixirField, Riddle Of Fire, Rising Phoenix and Meditation
- added low lvl aoe buffchecks and rotation
- added double solar opener
- add Dynamic TrueNorth to ST
- implement better Perfect Balance usage
- Implement better Beast Chakra usage

Will close #1056, #1348

### CODE REVIEW

**Comment by Kagekazu** [comment]
has been tested for 3 ish weeks now and have had no issues reported back. seems good for me.

Let me know if anything else needs to change just in case!

**Comment by rad96** [comment]
Checked build from you MNK branch
For some reason it does not weave forbidden chakra in opener, which leads to very heavy mantra overcap
Can you check?

**Comment by rad96** [comment]
Hi
I checked plugin built from you MNK branch
Why it does not weave forbidden chakra in opener?
In example, during Lunar Solar opener on a dummy you will have chakra limit before Elixir Field
But plugin not using it
It kinda not shown in The Balance opener graph, but you can refer to perfect balance video in example, where he uses Forbidden Chakra during opener to avoid overcap
https://youtu.be/cVkARdaslMQ?t=717
изображение

**Comment by Kagekazu** [comment]
> Hi I checked plugin built from you MNK branch Why it does not weave forbidden chakra in opener? In example, during Lunar Solar opener on a dummy you will have chakra limit before Elixir Field But plugin not using it It kinda not shown in The Balance opener graph, but you can refer to perfect balance video in example, where he uses Forbidden Chakra during opener to avoid overcap https://youtu.be/cVkARdaslMQ?t=717 изображение

That is correct. It is also not finished, hence the "in progress" tab :) rotation wise everything seems to behave, i just have to tweak the opener on behaving better

**Comment by tita9** [comment]
It would appear that meditation uptime is in a branch that conditionally checks for 5 chakras, but it has as a condition to have less than 5 chakras, therefore, it seems to never be reached ? Taking it out of these branches and putting it in an else if branch after the meditation spender branch fixed it for me.

**Comment by Kagekazu** [comment]
> It would appear that meditation uptime is in a branch that conditionally checks for 5 chakras, but its own branch has as a condition to have less than 5 chakras, therefore, it seems to never be reached ? Taking it out of these branches and putting it in an else if branch after the meditation spender branch fixed it for me.

That is also correct. It will be dealt with today or tomorrow when I find time to continue developing the rework.

**Comment by rad96** [comment]
@Kagekazu
why not just straight check chakra stack on entrance into opener or something like that? 
Because right now I see there is 3 usages of it during lunar solar
My logs, in example, in couple p12s pulls, shows that I can slap 5 forbidden chakras during opener
Here is example of some random log with guy doing 5 of them in double solar too 
изображение

https://xivanalysis.com/fflogs/6zY32rHa94nfgXcQ/35/21

**Comment by Kagekazu** [comment]
> @Kagekazu why not just straight check chakra stack on entrance into opener function or something like that? Because right now I see there is 3 usages of it during lunar solar My logs, in example, in couple p12s pulls, shows that I can slap 5 forbidden chakras during opener Here is example of some random log with guy doing 5 of them in double solar too изображение
> 
> https://xivanalysis.com/fflogs/6zY32rHa94nfgXcQ/35/21

I know it does, thats why it says "temp fix" since how it is programmed at the moment, i cant run the opener and have it check for 5 chakra's at the same time. so i'm looking at how i can change that.

Ideally i wanna make a function where it checks every step of the opener if it has 5 chakra's, if it does, weave in forbidden chakra, if it doesnt, continue to next step.

**Comment by tita9** [comment]
I built the changes into my own build and it looks gucci, I can't comment on rad's comments, I'm more of a casual, and am better at code than the game. :P

Will test more today, I'm leaving for two days afterwards, so far so good though.
Thank you for your patience and your time. :pray:

**Comment by rad96** [comment]
@Kagekazu here is a patch with fixes from @tita9 
[opener.patch](https://github.com/Nik-Potokar/XIVSlothCombo/files/14116143/opener.patch)
Looks somewhat better
I still clueless why now it can't get out of opener properly and reset fight, but I think that's different issue

**Comment by tita9** [comment]
> @Kagekazu here is a patch with fixes from @tita9 [opener.patch](https://github.com/Nik-Potokar/XIVSlothCombo/files/14116143/opener.patch) Looks somewhat better I still clueless why now it can't reset fight sometimes (or it always was like that after your changes), but I think that's different issue

I think that's an ACT issue, I definitely leave combat when I reset striking dummy enmity, but yeah I noticed skilldisplay wouldn't reset between fights when testing, it's why I had to crop the light party part.

**Comment by Kagekazu** [comment]
> > @Kagekazu here is a patch with fixes from @tita9 [opener.patch](https://github.com/Nik-Potokar/XIVSlothCombo/files/14116143/opener.patch) Looks somewhat better I still clueless why now it can't reset fight sometimes (or it always was like that after your changes), but I think that's different issue
> 
> I think that's an ACT issue, I definitely leave combat when I reset striking dummy enmity, but yeah I noticed skilldisplay wouldn't reset between fights when testing, it's why I had to crop the light party part.
> 
> Happy to look further into the opener if there's other problems with it.

If you are talking about resetting opener, i will have it re added after i check the code, cause i dont think it resets properly at the moment.

**Comment by Kagekazu** [comment]
@tita9 @rad96 changes have been pushed
should start using forbidden chakra after Demolish. I also added an opener check if u already have a Lunar or Solar Nadi, so if u have 1 already it wont trigger the opener.

Resetting should be better, probably not perfect yet.

**Comment by Kagekazu** [comment]
BTW @tita9 ur always welcome to PR to my MNK branch, might be easier

**Comment by tita9** [comment]
> BTW @tita9 ur always welcome to PR to my MNK branch, might be easier

I have no idea how to handle github lol ;o;
Will ask for help and learn, thanks for the invitation, very eager to contribute on stuff.

I tested the changes and it looks very gucci~ :D

**Comment by Kagekazu** [comment]
> > BTW @tita9 ur always welcome to PR to my MNK branch, might be easier
> 
> I have no idea how to handle github lol ;o; Will ask for help and learn, thanks for the invitation, very eager to contribute on stuff.
> 
> I tested the changes and it looks very gucci~ :D

Can always ask info in the discord server, might be easier to communicate than on a PR :D

**Pull request closed without merging**
