### PR TITLE
[WHM] Add Medica 2 Thin Air Feature - Use Thin Air before Medica 2

### PR DESCRIPTION
**Pull request by ryankhart**
I'm not sure what the best practices are for fitting in new presets into the CustomComboPreset.cs file, but I took the liberty to place my new CustomCombo just below the existing WHMMedicaFeature, both in the config UI and in the implementation. Also, to avoid duplicate IDs I changed the ID for WHMAlternativeRaise to reflect where it is in the CustomComboPreset.cs, right next to WHMAlternativeRaise. Let me know if you need me to make any changes.

### CODE REVIEW

**Comment by ryankhart** [comment]
It turns out it was just a couple line breaks that caused the conflicts. I had touched up some of the whitespace around the area to make it more consistent with the rest of the project, but apparently that caused conflicts.

**Comment by ryankhart** [comment]
I'm in the Discord server, yes.

Thanks for reaching out about the status on this PR! I can maybe help a little bit with existing issues, but I may not be able to test much yet, as don't have very many high-level jobs leveled yet (WHM to level 80, BRD, MCH, SAM, RDM to around level 50)

Documentation is an interest of mine. Maybe I can look over some of the existing features for WHM and submit a PR to make it clearer what each of them do.

I'm curious. How do you find Discord chat useful for anything other than socializing? I'm in almost 100 Discord servers and disable notifications in almost all of them. It seems like all the important information just gets drowned out and lost, and people (including people such as myself) end up asking questions that have already been answered a thousand times because the Discord search feature is so bad, and nothing on Discord is indexed by Google. Maybe I'm just still traumatized from getting Discord mods in other servers snap at me for asking questions.

I can take your examples from https://github.com/Nik-Potokar/XIVSlothCombo/pull/717 and start improving descriptions and feature names for WHM to better match your examples. When I start, I can open up a PR early, like you did, and then convert it to a draft. Unless you have a better idea.

**Review by NikkoXIV — CHANGES_REQUESTED** [review]
To do:
- [ ] restore original feature numbers
- [ ] remove WHMAlternativeRaise feature 19005 and related code (Keep WHMRaiseFeature 19004)
- [ ] add `!WasLastAction(ThinAir)` to the if conditions
- [ ] add the Thin Air code to the existing `WHMMedicaFeature` class

**Comment by k-kz** [comment]
Added "Medica 2 Thin Air" in #847

**Pull request closed without merging**
