### PR TITLE
WIP: chore(AST): re-work ast class

### PR DESCRIPTION
**Pull request by ele-starshade**
- [x] Test it!
- [ ] Do others

### CODE REVIEW

**Comment by Iaotle** [comment]
Wow, good job! You're doing a lot of good work.

**Comment by augporto** [comment]
Hello @ele-starshade, @Iaotle  would you guys like some help to replicate this rework on the other jobs ? I really like it 👍

**Comment by Iaotle** [comment]
@augporto I think we need to add the Dictionary to some global or something so we can use it for all jobs, will prevent us from having to make one per job.

Otherwise, I might have time end of next week to work on something. Not sure tbh, I got uni.

**Comment by Iaotle** [comment]
One other thing, maybe we can have a `ReturnIfUnlocked(spell, level)` func in order to simplify the logic. That way it will return 0 if not unlocked, and spell ID if it is.

**Comment by augporto** [comment]
> @augporto I think we need to add the Dictionary to some global or something so we can use it for all jobs, will prevent us from having to make one per job.
> 
> Otherwise, I might have time end of next week to work on something. Not sure tbh, I got uni.

Yea I was thinking about that too, maybe a global class Job that others can use with inheritance to centralize normal functions and shared variables like that action dictionary to all jobs like the unlock checks , to not need to rewrite the same function on all classes again. But initialization would be per Job based , or else we would have a ginormous initialization.

> One other thing, maybe we can have a `ReturnIfUnlocked(spell, level)` func in order to simplify the logic. That way it will return 0 if not unlocked, and spell ID if it is.

That seems good too.

**Comment by Iaotle** [comment]
This should be more of a maintenance thing tbh, I believe the codebase changes here are great if someone wants to pick it up @k-kz

**Comment by k-kz** [comment]
I've created a 'placeholder' version of this, disconnected from AST on a branch of my fork for posterity, but at this point I think we've superseded the need for a `Levels` dictionary (we no longer need to store level constants at all, when using `LevelChecked()`), so I'll be closing this.

https://github.com/k-kz/XIVSlothCombo/blob/dictionary/XIVSlothCombo/ActionDictionary.cs

**Pull request closed without merging**
