### PR TITLE
Warrior fixes

### PR DESCRIPTION
**Pull request by sauronshotdogs**
Fixed OnslaughtOptionTwo and adjusted description. Now leaves 1 charge below 88.

Moved Orogeny combo up, so it will activate in time with Upheaval. Will still wait for Storm's buff

Attempt at cleaning up my ugly formatting

### CODE REVIEW

**Comment by Codemned** [comment]
It's nice that your trying to learn this and I'd like to give you some feedback, I hope you don't mind.

**Comment by sauronshotdogs** [comment]
Of course!

**Comment by Codemned** [comment]
2 stack option probably needs "if (level >= 62 && level <= 87)" or someone level 88+ would qualify for both arguments bugging the feature.

**Comment by sauronshotdogs** [comment]
Will Try to add that. It works though. I found the order in which the code would appear to be most important, and I wasn't sure how to force the order with arguments

**Pull request merged**
