### PR TITLE
DRK level 100

### PR DESCRIPTION
**Pull request by zbee**
With 7.0 DRK is a bit different overall, mostly due to a shift in how Delirium+Blood weapon stacks an timer are used.

- [X] Enable DRK
- [X] Update Action IDs
- [X] Add New Action IDs
- [X] Rework Combo options to make them more consistent with each other
- [X] Add option to ST>Living Dead to prevent it based on target %remainingHP (similar WHM option [here](https://github.com/Nik-Potokar/XIVSlothCombo/blob/06abee27d81e482c90b2c9c736e8e5db07ff1f94/XIVSlothCombo/Combos/PvE/WHM.cs#L281))
- [X] Add _separate_ option to AoE>Living Dead to prevent it based on target %remainingHP
- [X] Un-break Combo code
- [X] Update Combo code to 7.0 changes (no Blood Weapon, etc)
- [X] Add options for Disesteem use
- [X] Add level 100 actions into Combo code
- [X] Add new options into Combo code
- [X] Reorganize oGCDs in the Combo code to try to mitigate false positive Dark Arts reports preventing all other oGCDs from working
- [X] Organize Combo code to hopefully put out The Balance's [Standard Opener](https://discord.com/channels/277897135515762698/277962421862268930/1257508528357376060)
- [X] ~~Rework Combo Code to make it more consistent between combos~~
- [X] ~~Rework Delirium+Mana usage to build Mana on Odd minute windows~~
- [X] ~~Rework Combo options+code to reflect the new 'Simple' setup other classes are getting~~
- [X] ~~Update PVP for DRK~~
- [X] ~~Wipe existing configs (DNC did this [here](https://github.com/Nik-Potokar/XIVSlothCombo/pull/1266/commits/342996f3b9c53038938dafeee5e9a9805413baeb))~~

> [!caution]
> #### Inconsistent without ClientStructs+Dalamud updating DRK job gauge.
> Does not respect the user's chosen MP limit under Option#12 in some situations.
>
> <sub>No update should be needed here once those are updated and version bumped.</sub>

### CODE REVIEW

**Comment by Tartarga** [comment]
If I could recall, configs should be wiped already

**Comment by zbee** [comment]
Working version done.
Needs in-game testing, and some consistency changes before it's ready.

**Comment by zbee** [comment]
Even-minute burst windows and filler content are perfect.
Odd-minute bursts (and even worse for every Delirium use during AoE), however, interrupt the Torcleaver combo:
image

**Comment by zbee** [comment]
Ready for review, @Taurenkey.

> [!caution]
> Inconsistent without ClientStructs+Dalamud updating DRK job gauge.
> Does not respect the user's chosen MP limit in some situations.
> No update should be needed here once those are updated and version bumped.

^ DRK works, and quite well, but at times it acts as though Dark Arts is available and will dump all your mana.

**Pull request merged**
