### PR TITLE
[SCH] Scholar feature improvement

### PR DESCRIPTION
**Pull request by jundong321**
New Features:
- SCH_Lustrate: Change `Lustrate` into `Excogitation` when `Excogitation` is ready.
- SCH_Recitation: Change `Recitation` into one of `Adloquium`, `Succor`, `Indomitability`, and `Excogitation`.

### CODE REVIEW

**Comment by k-kz** [comment]
Will be taking a proper look at this with @Tartarga once #908, #914 and #926 are merged - it looks good for the most part but we'll need to do some conflict avoidance after his stuff goes through, I'm pretty sure.

**Comment by Tartarga** [comment]
@jundong321 Lustrate looks good to me, but I have a question on Recitation. Are the options for Recitation supposed to be a "Choose only one of the four options" sort of thing? (Comparing your code with your description)

**Comment by k-kz** [comment]
> Lustrate looks good to me, but I have a question on Recitation. Are the options for Recitation supposed to be a "Choose only one of the four options" sort of thing? (Comparing your code with your description)

To add to this, it seems like it might be a better approach to create a multi-checkbox which allows `Recitation` to be placed over any combination of the four skills - that way, you can add it to the skills you'd like and use it in a more flexible manner when in combat by double-tapping the relevant action.

(I should probably note that I don't play SCH and might be misunderstanding the intended use, but I'm under the impression that `Recitation` is to be used before the other skills in order to buff them in some way)

**Comment by jundong321** [comment]
> > Lustrate looks good to me, but I have a question on Recitation. Are the options for Recitation supposed to be a "Choose only one of the four options" sort of thing? (Comparing your code with your description)
> 
> To add to this, it seems like it might be a better approach to create a multi-checkbox which allows `Recitation` to be placed over any combination of the four skills - that way, you can add it to the skills you'd like and use it in a more flexible manner when in combat by double-tapping the relevant action.
> 
> (I should probably note that I don't play SCH and might be misunderstanding the intended use, but I'm under the impression that `Recitation` is to be used before the other skills in order to buff them in some way)

Thanks for the suggestion! What you described is one approach, and I think it's already there. The other approach is to have recitation changed to one of the four skills, so that you can double tap the recitation button to use the combo. It will allow only one of the combos though, so the flexibility is limited.
The reason I choose this approach is that I try to avoid covering the healing skills with other skills, so that the button press is a more defined behavior for these skills. Like sometimes I press two times to heal and sometimes I press one time to heal.
But I totally agree that this is a choose one of the four feature, and would be nice to have an exclusive select. I will add feature conflicts to do that.

**Comment by k-kz** [comment]
Please feel free to send a message on discord if you'd like to talk with us about it in greater depth :)

**Comment by jundong321** [comment]
@Tartarga the suggested code change is in, tested working as expected.

**Comment by Tartarga** [comment]
Just tried it out, everything plays great, but the only issue I had was Excog and Succor values being mixed (top is userconfig.cs, bottom is SCH.cs)
image

**Pull request merged**
